CREATE DATABASE `university` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;
CREATE TABLE `course` (
  `CNUM` int(11) NOT NULL,
  `CNAME` varchar(45) DEFAULT NULL,
  `CDESC` varchar(45) DEFAULT NULL,
  `CREDIT` int(11) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `CDEPT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `department` (
  `DEPTNAME` varchar(45) DEFAULT NULL,
  `DEPTPHONE` int(11) DEFAULT NULL,
  `DEPTOFFICE` varchar(45) DEFAULT NULL,
  `DEPTCOLLEGE` varchar(45) DEFAULT NULL,
  `DEPTCODE` int(11) NOT NULL,
  PRIMARY KEY (`DEPTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `grade` (
  `SSN` int(11) NOT NULL,
  `GRADE` int(11) DEFAULT NULL,
  `CNUM` varchar(45) DEFAULT NULL,
  `SECNUM` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SSN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `section` (
  `SECNUM` int(11) NOT NULL,
  `INSTNAME` varchar(45) DEFAULT NULL,
  `SEM` varchar(45) DEFAULT NULL,
  `YEAR` int(11) DEFAULT NULL,
  `SECCOURSE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SECNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `student` (
  `SSN` int(11) NOT NULL,
  `SNAME` varchar(45) DEFAULT NULL,
  `SPADDR` varchar(45) DEFAULT NULL,
  `SPHONE` varchar(45) DEFAULT NULL,
  `BDATE` datetime DEFAULT NULL,
  `SEX` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SSN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `university` (
  `SNAME` int(11) NOT NULL,
  `SNUM` int(11) NOT NULL,
  `SCADDR` varchar(45) DEFAULT NULL,
  `SCPHONE` varchar(45) DEFAULT NULL,
  `CLASS` varchar(45) DEFAULT NULL,
  `MAJORDEPTCODE` int(11) DEFAULT NULL,
  `MINORDEPTCODE` int(11) DEFAULT NULL,
  `PROG` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SNAME`,`SNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
